http:
  routers:
    frontend-demo1:
      rule: "Host(`demo1.kalvixnexus.com`)"
      service: frontend
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
    backend-demo1:
      rule: "Host(`api.demo1.kalvixnexus.com`)"
      service: backend
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
